routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['prefix' => LaravelLocalization::setLocale(),
    'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
],
    function()
{
    //Головна сторінка сайту
    Route::get('/', 'ClockController@mainPage')->name('main');
    Route::get('/shop', 'ClockController@shopPage')->name('shop');
    Route::get('/shop/{id}', 'ClockController@show');
    Route::get('checkout', ['uses' => 'OrderController@create', 'as' => 'checkout']);
    Route::get('checkout/success', ['uses' => 'OrderController@success', 'as' => 'checkoutSuccess']);

    // Localization in Vue
    Route::get('/js/lang.js', 'LocalizationController@getLocalizationFile')->name('assets.lang');
});


Route::get('filter', 'ClockController@filter')->name('filter');
Route::post('orders', 'OrderController@store')->name('newOrder');
Route::post('feedbacks', 'FeedbackController@store')->name('new-feedback');
Route::post('cart/add', ['uses' => 'ClockController@addToCart', 'as' => 'addToCart']);
Route::post('cart/update', ['uses' => 'ClockController@updateCart', 'as' => 'updateCart']);
Route::post('cart/remove', ['uses' => 'ClockController@removeFromCart', 'as' => 'removeFromCart']);
Route::get('cart', ['uses' => 'ClockController@getCart', 'as' => 'getCart']);
Route::get('nova-poshta/get-warehouses', 'OrderController@getWarehouses');
Route::post('nova-poshta/get-warehouses', 'OrderController@getWarehouses');



Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');
Auth::routes();
Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function (){
    Route::get('/', 'AdminController@index');

    Route::put('clocks/{id}/update', 'ClockController@updateFromTable');
    Route::delete('clocks/{id}/destroy', 'ClockController@destroyFromTable');
    Route::post('clocks/images/set-logo/{id}', 'ClockController@setLogo');
    Route::post('clocks/images/{id}', 'ClockController@loadImages');
    Route::delete('clocks/images/{id}', 'ClockController@deleteImage');
    Route::put('clocks/descriptions/{id}', 'ClockController@setDescriptions');
    Route::post('clocks/descriptions/{id}', 'ClockController@getDescriptions');
    Route::put('clocks/characteristics/{id}', 'ClockController@setCharacteristics');
    Route::post('clocks/characteristics/{id}', 'ClockController@getCharacteristics');
    Route::resource('clocks', 'ClockController');

    Route::get('orders/old', ['uses' => 'OrderController@oldOrders', 'as' => 'oldOrders']);
    Route::resource('orders', 'OrderController');

    Route::get('feedbacks/old', 'FeedbackController@oldFeedbacks');
    Route::resource('feedbacks', 'FeedbackController');



});

Route::get('/home', 'HomeController@index')->name('home');

resources/views/admin/addOrUpdateClock.blade.php
@extends('admin.layouts.app')

@section('content')

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    @if (! isset($data['clock_id']))
        <clock-form></clock-form>
    @else
        <clock-form v-bind:clock-data='{!! json_encode($data) !!}'
                    v-bind:update-url='"{!! url("/admin/clocks")."/".$data["clock_id"] !!}"'
        ></clock-form>
        <ul class="nav nav-tabs" id="tabList" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" id="descriptions-tab" data-toggle="tab" href="#descriptions" role="tab" aria-controls="descriptions" aria-selected="true">Опис</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="characteristics-tab" data-toggle="tab" href="#characteristics" role="tab" aria-controls="characteristics" aria-selected="false">Характеристики</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="images-tab" data-toggle="tab" href="#images" role="tab" aria-controls="images" aria-selected="false">Зображення</a>
            </li>
        </ul>
        <div class="tab-content" id="myTabContent">
            <div class="tab-pane fade  show active" id="descriptions" role="tabpanel" aria-labelledby="descriptions-tab">
                <descriptions-form v-bind:descriptions-data='{!! json_encode($data["descriptions"]) !!}'
                                   v-bind:update-url='"{!! url("/admin/clocks/descriptions")."/".$data["clock_id"] !!}"'
                ></descriptions-form>
            </div>

            <div class="tab-pane fade" id="characteristics" role="tabpanel" aria-labelledby="characteristics-tab">
                <characteristics-form v-bind:characteristics-data='{!! json_encode($data["characteristics"]) !!}'
                                      v-bind:functions-data='{!! json_encode($data["functions"]) !!}'
                                      v-bind:update-url='"{!! url("/admin/clocks/characteristics")."/".$data["clock_id"] !!}"'
                ></characteristics-form>
            </div>

            <div class="tab-pane fade" id="images" role="tabpanel" aria-labelledby="images-tab">
                <images-form v-bind:images-data='{!! json_encode($data["images"]) !!}'
                             v-bind:logo='{!! json_encode($data["logo_uuid"]) !!}'
                             v-bind:update-url='"{!! url("/admin/clocks/images")."/".$data["clock_id"] !!}"'
                             v-bind:set-logo-url='"{!! url("/admin/clocks/images/set-logo")."/".$data["clock_id"] !!}"'
                             v-bind:images-path='"{!! url("/images/medium")."/" !!}"'

                ></images-form>
            </div>
        </div>
    @endif


@endsection
@section('scripts')
    <script>
    </script>


@endsection

resources/views/admin/admin.blade.php
@extends('admin.layouts.app')

@section('content')
    контент
@endsection

@section('scripts')
    <script>

    </script>

@endsection

resources/views/admin/clocksTable.blade.php
@extends('admin.layouts.app')

@section('content')


    <clocks-table>
    </clocks-table>


@endsection
@section('scripts')
    <script>
        var clockUrl = "{!! url('/admin/clocks') !!}";
        var data = {!! json_encode($data) !!};
    </script>


@endsection

resources/views/admin/feedbacksTable.blade.php
@extends('admin.layouts.app')

@section('content')


    <feedbacks-table v-bind:feedbacks-data='{!! $data !!}'
                  v-bind:feedbacks-url='"{!! route('feedbacks.index') !!}"'>
    </feedbacks-table>


@endsection
@section('scripts')
    <script>
    </script>


@endsection

resources/views/admin/orderDetails.blade.php
@extends('admin.layouts.app')

@section('content')

    <div id="adminOrder" class="mt-3">
        <div class="form-group row">
            <div class="col-lg-12">
                <table class="table table-sm">
                    <tbody>
                        <tr>
                            <th>Замовлення №</th>
                            <td>{{$data['order_id']}}</td>
                        </tr>
                        <tr>
                            <th>Час | Дата</th>
                            <td>{{$data['created_at']}}</td>
                        </tr>
                        <tr>
                            <th>Ім'я</th>
                            <td>{{$data['client_first_name']}}</td>
                        </tr>
                        <tr>
                            <th>Прізвище</th>
                            <td>{{$data['client_last_name']}}</td>
                        </tr>
                        <tr>
                            <th>Номер телефону</th>
                            <td>0{{$data['phone']}}</td>
                        </tr>
                        <tr>
                            <th>Місто</th>
                            <td>{{$data["city"]["Present"] ?? "Невизначено"}}</td>
                        </tr>
                        <tr>
                            <th>Метод доставки</th>
                            <td>{{trans('localization.'.$data['delivery_method'], [], 'uk')}}</td>
                        </tr>
                        <tr>
                            <th>Відділення</th>
                            <td>{{$data["warehous"]["Description"] ?? $data["warehous"]}}</td>
                        </tr>
                        <tr>
                            <th>Метод оплати</th>
                            <td>{{trans('localization.'.$data['pay_method'], [], 'uk')}}</td>
                        </tr>
                        <tr>
                            <th>Разом до оплати</th>
                            <td>{{$data['total_price']}} грн</td>
                        </tr>
                        @if ($data['revised'])
                            <tr>
                                <th>Статус</th>
                                <td class="text-success">Переглянуто</td>
                            </tr>
                            <tr>
                                <th>Час перегляду</th>
                                <td>{{$data['updated_at']}}</td>
                            </tr>
                        @else
                            <tr>
                                <th>Статус</th>
                                <td class="text-danger">Не переглянуто</td>
                            </tr>
                        @endif

                    </tbody>
                </table>

                <table id="cartTable" class="table table-sm mt-5 mb-0">
                    <thead>
                        <tr>
                            <th scope="col"></th>
                            <th scope="col">Назва товару</th>
                            <th scope="col">Ціна</th>
                            <th scope="col">Кількість</th>
                            <th scope="col">Сума</th>
                        </tr>
                    </thead>
                    <tbody>

                    @foreach($cart as $item)
                        <tr>
                            <td class="logo-cell">
                                <a href="{{route('clocks.show', ['id' => $item['clock_id']])}}" target="_blank">
                                    <img src="{{ url('images/small').'/'.$item['clock']['logo_uuid']}}" class="img-fluid img-thumbnail logo" alt="Responsive image">
                                </a>
                            </td>
                            <td>
                                <div class="product-name">
                                    <a href="{{route('clocks.show', ['id' => $item['clock_id']])}}" target="_blank">{{$item['clock']['name']}}</a>
                                </div>
                            </td>
                            <td>{{$item['clock']['price']}} грн</td>
                            <td>{{$item['qty']}} шт.</td>
                            <td>{{$item['clock']['price'] * $item['qty']}} грн</td>
                        </tr>
                    @endforeach

                    </tbody>
                </table>
                <div class="d-flex justify-content-end">
                    <span class="order-total-price">Разом до оплати: {{$data['total_price']}} грн</span>
                </div>
            </div>
        </div>
        <div id="visited" class="row mb-5">
            <div class="col-2">
                <form action="{!! route('orders.update', ['id' => $data['order_id']]) !!}" method="post">
                    {{ csrf_field() }}
                    <input type="hidden" name="_method" value="PUT">
                    @if ($data['revised'] == 0)
                        <input type="hidden" name="revised" value=1>
                        <input class="btn btn-success w-100" type="submit" value="Переглянуто">
                    @endif
                </form>
            </div>
        </div>

    </div>


@endsection
@section('scripts')
    <script >

    </script>


@endsection

resources/views/admin/ordersTable.blade.php
@extends('admin.layouts.app')

@section('content')


    <orders-table v-bind:orders-data='{!! json_encode($data) !!}'
                  v-bind:orders-url='"{!! route('orders.index') !!}"'>
    </orders-table>


@endsection
@section('scripts')
    <script>
    </script>


@endsection